"""
index_exclusions.py
-------------------
Brand-name sets for major stock / revenue indices.
Used by signal_scout.py to exclude large public companies that are unlikely
to engage a boutique consultancy (S&P 500, Fortune 500, FTSE 100).

Names are lowercase, stripped of legal suffixes (Inc., Corp., plc, Ltd., etc.)
to maximise match recall against news-article company mentions.

Sources: index constituents as of early 2025 (refreshed periodically).
"""

# ---------------------------------------------------------------------------
# S&P 500  — US large-cap index
# ---------------------------------------------------------------------------
SP500_COMPANIES: set[str] = {
    "3m", "a.o. smith", "abbott laboratories", "abbvie", "accenture",
    "activision blizzard", "adobe", "advance auto parts", "aes",
    "aflac", "agilent technologies", "air products", "airbnb",
    "akamai", "alaska air", "albemarle", "alexandria real estate",
    "align technology", "allegion", "allergan", "alliant energy",
    "allstate", "alphabet", "altria", "amazon", "amcor",
    "amdocs", "ameriprise financial", "amerisourcebergen",
    "ametek", "amgen", "amphenol", "analog devices",
    "ansys", "aon", "apache", "apple", "applied materials",
    "aptiv", "arista networks", "arthur j gallagher", "assurant",
    "astrazeneca", "at&t", "atmos energy", "autodesk", "automatic data processing",
    "autozone", "avalonbay communities", "avery dennison", "axa",
    "baker hughes", "ball", "bank of america", "baxter international",
    "becton dickinson", "berkshire hathaway", "best buy", "biogen",
    "bio-rad laboratories", "biomet", "black hills", "blackrock",
    "boeing", "borgwarner", "boston properties", "boston scientific",
    "bristol-myers squibb", "broadcom", "broadridge financial",
    "brown & brown", "brown-forman", "cabot oil & gas", "cadence design",
    "caesars entertainment", "camden property", "campbell soup",
    "capital one", "cardinal health", "carmax", "carrier global",
    "catalent", "caterpillar", "cboe global markets", "cbre",
    "cdw", "celanese", "centene", "centerpoint energy",
    "ceridian hcm", "cf industries", "charles river laboratories",
    "charles schwab", "charter communications", "chevron",
    "church & dwight", "cigna", "cintas", "cisco",
    "citigroup", "citizens financial", "clorox", "cms energy",
    "coca-cola", "cognizant", "copart", "corning",
    "corteva", "costar", "costco", "coterra energy",
    "crown castle", "crown holdings", "csx", "cummins",
    "cvs health", "d.r. horton", "data realty trust", "davita",
    "deere", "delta air lines", "devon energy", "digital realty",
    "discover financial", "disney", "dollar general", "dollar tree",
    "dominion energy", "domino's pizza", "dover", "dowdupont",
    "dun & bradstreet", "dupont", "dxc technology", "eastman chemical",
    "eaton", "ebay", "ed eaton", "edwards lifesciences", "electric arts",
    "eli lilly", "emerson electric", "entegris", "entergy",
    "eog resources", "epam systems", "equifax", "equinix",
    "equity residential", "estee lauder", "evergy", "eversource",
    "exelon", "expedia", "expeditors", "extra space storage",
    "exxon mobil", "f5", "factset", "fastenal", "fidelity national",
    "fiserv", "flir systems", "fluor", "ford motor",
    "fortive", "fortinet", "fox", "franklin resources",
    "freeport-mcmoran", "gartner", "general dynamics", "general electric",
    "general mills", "general motors", "genuine parts",
    "gilead sciences", "global payments", "globe life",
    "goldman sachs", "grainger", "halliburton", "hartford financial",
    "hasbro", "hca healthcare", "healthpeak properties",
    "henry schein", "hershey", "hess", "hewlett packard enterprise",
    "hilton worldwide", "홈 depot", "home depot", "honeywell",
    "host hotels", "hp", "humana", "huntington bancshares",
    "huntington ingalls", "idexx laboratories", "illinois tool works",
    "illumina", "incyte", "intel", "intercontinental exchange",
    "international flavors", "international paper", "interpublic",
    "intuit", "intuitive surgical", "invesco", "iqvia",
    "iron mountain", "j.b. hunt transport", "j.m. smucker",
    "jacobs engineering", "johnson & johnson", "johnson controls",
    "jpmorgan chase", "juniper networks", "kellogg", "keycorp",
    "keysite technologies", "kimberly-clark", "kimco realty",
    "kraft heinz", "kroger", "l3harris technologies", "labcorp",
    "laboratory corporation", "las vegas sands", "leidos",
    "lennar", "lincoln national", "live nation", "lkq",
    "lockheed martin", "loews", "lowe's", "lululemon",
    "lyondellbasell", "m&t bank", "marathon oil", "marathon petroleum",
    "marsh & mclennan", "mastercard", "mccormick", "mcdonald's",
    "mckesson", "medtronic", "merck", "metlife",
    "mettler-toledo", "microchip technology", "micron technology",
    "microsoft", "mid-america apartment", "mohawk industries",
    "molina healthcare", "molson coors", "mondelez", "monsanto",
    "moody's", "morgan stanley", "motorola solutions",
    "msci", "nasdaq", "national fuel gas", "netflix",
    "neustar", "new york times", "newmont", "news corp",
    "nextera energy", "nielsen", "nike", "nordstrom",
    "norfolk southern", "northrop grumman", "nvr", "nvidia",
    "nxp semiconductors", "occidental petroleum", "okta", "old dominion freight",
    "omnicom", "oneok", "oracle", "o'reilly automotive",
    "otis worldwide", "packaging corp", "parker hannifin",
    "paychex", "paycom", "paypal", "pentair",
    "pepsico", "perkinelmer", "pfizer", "philip morris",
    "phillips 66", "pinnacle west", "pioneer natural resources",
    "pkh", "plug power", "pnc financial", "ppg industries",
    "ppl", "principal financial", "procter & gamble",
    "progressive", "prologis", "prudential financial", "pseg",
    "public storage", "pultegroup", "pvh", "qualcomm",
    "quest diagnostics", "raytheon technologies", "realty income",
    "regency centers", "regeneron", "regions financial",
    "republic services", "resmed", "robert half", "rockwell automation",
    "rollins", "roper technologies", "ross stores", "royal caribbean",
    "s&p global", "salesforce", "seagate technology", "sealed air",
    "servicenow", "signature bank", "simon property", "skyworks",
    "sl power electronics", "snap-on", "southern company",
    "southwest airlines", "stanley black & decker",
    "state street", "steris", "stryker", "svb financial",
    "synchrony financial", "sysco", "t. rowe price", "t-mobile",
    "take-two interactive", "tapestry", "target", "te connectivity",
    "teleflex", "tesla", "texas instruments", "textron",
    "thermo fisher scientific", "tiffany", "tjx", "torchmark",
    "tractor supply", "transferwise", "travelers", "truist financial",
    "tyson foods", "u.s. bancorp", "uber technologies",
    "ulta beauty", "union pacific", "united airlines",
    "united parcel service", "united rentals", "united states steel",
    "unitedhealth", "universal health services", "ups",
    "unum group", "valero energy", "varian medical",
    "verizon", "vertex pharmaceuticals", "vf", "viavi solutions",
    "visa", "vmc", "vulcan materials", "w.r. berkley",
    "walgreens boots alliance", "walmart", "walt disney",
    "waste management", "waters", "wellsfargo", "wells fargo",
    "westinghouse", "westrock", "weyerhaeuser", "whirlpool",
    "williams companies", "willis towers watson", "wynn resorts",
    "xcel energy", "xylem", "yum! brands", "zimmer biomet",
    "zions bancorporation", "zoetis", "zoom video",
    # Recent additions / large-cap tech
    "amd", "advanced micro devices", "airbnb", "coinbase",
    "crowdstrike", "datadog", "docusign", "fortinet",
    "hubspot", "mongodb", "palo alto networks", "palantir",
    "pinterest", "roblox", "snowflake", "spotify",
    "square", "block", "stripe", "twilio", "workday",
}

# ---------------------------------------------------------------------------
# Fortune 500 — US largest companies by revenue (adds non-S&P private firms)
# ---------------------------------------------------------------------------
FORTUNE500_COMPANIES: set[str] = SP500_COMPANIES | {
    # Large private / non-publicly-listed US companies commonly in Fortune 500
    "cargill", "koch industries", "deloitte", "pwc",
    "pricewaterhousecoopers", "ernst & young", "ey", "kpmg",
    "mckinsey", "bain", "bcg", "boston consulting group",
    "accenture", "berkshire hathaway", "liberty mutual",
    "state farm", "usaa", "nationwide", "army & air force exchange",
    "publix", "h-e-b", "meijer", "love's travel stops",
    "pilot flying j", "enterprise holdings", "reyes holdings",
    "aldi", "menard", "jm family enterprises",
    "abc supply", "wawa", "bechtel", "turner construction",
    "fluor", "jacobs", "dick's sporting goods",
    "military exchange", "ssc", "levi strauss",
    "american family insurance", "guardian life",
    "mutual of omaha", "nypd", "pacific life",
    "unum", "ameritas", "securian financial",
    "iac", "hilton", "marriott", "hyatt", "wyndham",
    "mgm resorts", "caesars", "booking holdings",
    "expedia", "airbnb", "doordash", "instacart",
    "lyft", "grubhub", "robinhood",
    # Large healthcare/pharmacy
    "cigna", "humana", "anthem", "elevance health",
    "centene", "molina healthcare", "davita",
    "davita kidney care", "kindred healthcare",
    "tenet healthcare", "community health systems",
    "hca", "fresenius", "lhc group",
    # Large retail
    "amazon", "walmart", "costco", "kroger", "target",
    "home depot", "lowe's", "walgreens", "cvs",
    "dollar general", "dollar tree", "ross stores", "tjx",
    "gap", "l brands", "nordstrom", "macy's",
    "kohl's", "bed bath & beyond", "best buy",
    "autozone", "advance auto", "o'reilly",
    # Large energy
    "exxon", "chevron", "conocophillips", "phillips 66",
    "valero", "marathon petroleum", "hess", "pioneer",
    "devon", "occidental", "halliburton", "schlumberger",
    "slb", "baker hughes", "williams", "kinder morgan",
    "oneok", "enterprise products", "energy transfer",
    # Large financials
    "jpmorgan", "bank of america", "wells fargo", "citigroup",
    "goldman sachs", "morgan stanley", "blackrock",
    "american express", "capital one", "discover",
    "ally financial", "synchrony", "citizens",
    "regions", "fifth third", "keycorp", "m&t bank",
    "huntington", "zions", "comerica", "cullen/frost",
}

# ---------------------------------------------------------------------------
# FTSE 100 — UK large-cap index
# ---------------------------------------------------------------------------
FTSE100_COMPANIES: set[str] = {
    "admiral", "astrazeneca", "associated british foods", "auto trader",
    "aviva", "b&m european value retail", "baae systems", "bae systems",
    "barclays", "barratt developments", "bhp", "bp",
    "british american tobacco", "bt", "bunzl", "burberry",
    "centrica", "coca-cola hbc", "compass", "crh",
    "croda international", "sse", "dcc", "diageo",
    "ds smith", "easyjet", "endeavour mining", "entain",
    "experian", "ferguson", "fresnillo", "glencore",
    "glaxosmithkline", "gsk", "haleon", "halma",
    "hargreaves lansdown", "hikma pharmaceuticals",
    "hsbc", "imi", "imperial brands", "informa",
    "intercontinental hotels", "intermediate capital",
    "international consolidated airlines", "intertek",
    "jd sports", "kingfisher", "land securities", "legal & general",
    "lloyds banking group", "london stock exchange", "m&g",
    "marks & spencer", "melrose industries", "mondi",
    "national grid", "natwest", "next", "nio",
    "ocado", "pearson", "pershing square holdings",
    "persimmon", "phoenix", "prudential", "reckitt",
    "reckitt benckiser", "relx", "rentokil initial",
    "rightmove", "rio tinto", "rolls-royce", "sage",
    "sainsbury's", "schroders", "scottish mortgage investment trust",
    "segro", "shell", "smurfit kappa", "spirax-sarco",
    "st james's place", "standard chartered", "taylor wimpey",
    "tesco", "3i", "travis perkins", "unilever",
    "united utilities", "vodafone", "weir", "whitbread",
    "wpp", "abrdn", "airtel africa", "antofagasta",
    "ashtead", "asos", "aveva", "beazley",
    "berkeley", "carnival", "clarivate", "coca-cola europacific",
    "direct line", "drax", "electrocomponents", "endeavour",
    "games workshop", "hammerson", "hiscox", "howden joinery",
    "itv", "j sainsbury", "johnsons matthey", "johnson matthey",
    "just eat takeaway", "kingspan", "landsec", "man",
    "meggitt", "micropole", "network international",
    "ninety one", "np", "pagegroup", "paragon banking",
    "pets at home", "phoenix", "polymetal", "primrose",
    "qinetiq", "redrow", "restore", "rpc",
    "senior", "serco", "ssp", "superdry",
    "synthomer", "tempur sealy", "tullow oil", "victrex",
    "virgin money", "vivo energy", "warehouse reit",
    "wood", "workspace",
}

# ---------------------------------------------------------------------------
# Combined index set (for easy single-call lookup)
# ---------------------------------------------------------------------------
ALL_INDEX_COMPANIES: set[str] = SP500_COMPANIES | FORTUNE500_COMPANIES | FTSE100_COMPANIES
